
server:
  port: 8000
  servlet:
    context-path: / #localhost:8000/가 들어감
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: zero
    password: zero
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 5
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #최초에만 create로, 나머지는 update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #model에 있는 변수값과 같은 이름으로 데이터에 들어감
      use-new-id-generator-mappings: false
    show-sql: true #콘솔창에 sql 보여줌
    properties:
      hibernate.format_sql: true #콘솔창에 sql문 정렬되게 보여줌
    database: oracle

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
        